services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pehlione_go
      MYSQL_USER: musta
      MYSQL_PASSWORD: pehlione
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

volumes:
  mysqldata: {}
